name: Generate and push an SBOM dependency list

on:
  push:
    # Only when tagging a new version which will be deployed
    tags:
      - '*'
  workflow_dispatch:

jobs:
  generate-and-push-sbom:
    uses: hitobito/hitobito/.github/workflows/sbom.yml@master
    with:
      project_name: hitobito-cevi
